### ISSUE TITLE
Active tag?

### ISSUE THREAD

**Issue by jamine16** [z4ziggy/Zigfrid#1]
Hi, I have successfully built some passive tags.

I was wondering if it possible to use a smaller antenna and power the MCU via a CR2032 battery using a push button to turn it on and off.

**Comment by z4ziggy** [comment]
regarding the antenna - as long it will match the wavelength, it will work.
regarding the battery - sure will. I've used battery on my testings, so you should be fine. maybe some minor changes in the code to use new the power advantages, save/restore last id, etc... 

g'luck

**Comment by jamine16** [comment]
Thanks, I will give it a try and come back with my results.
